### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by gvivek19** [gvivek19/fss16c#3]
- [x] get the effort predicted in a text file
- [x] calculate all 3 error measures mentioned in the paper (AR, MRE, +1)
- [x] output to a text file
- [x] pass this to skott knott

- [x] config file

- [x] charts/visualization
- [x] pip

**Comment by gvivek19** [comment]
http://marthall.github.io/blog/how-to-package-a-python-app/
https://python-packaging.readthedocs.io/en/latest/minimal.html

**Comment by gvivek19** [comment]
Install: sudo python setup.py install
Uninstall: pip uninstall effort_estimators
